    [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"
  
  [[main]]
  name = "Murmur"
  weight = 300
  identifier = "murmur"
  url = "/murmur/"

  [[main]]
  name = "Portfolio"
  weight = 400
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Tags"
  weight = 600
  identifier = "tags"

  [[main]]
  name = "Daily Life"
  weight = 610
  identifier = "dailylife"
  url = "/tags/dailylife/"
  parent = "tags"  

#  [[main]]
#  name = "Accomplishments"
#  weight = 500
#  identifier = "accomplishments"

#  [[main]]
#  name = "Awards"
#  weight = 510
#  identifier = "awards"
#  url = "/awards/"
#  parent = "accomplishments"  

#  [[main]]
#  name = "Certifications"
#  weight = 520
#  identifier = "certifications"
#  url = "/certifications/"
#  parent = "accomplishments"

#  [[main]]
#  name = "Contact"
#  weight = 600
#  identifier = "contact"
#  url = "/contact/"
